Repository Arquisoft/dede_es5a, pull requests merged in 2022-03, with the labels that each got.

#67 Creado un CRUD funcional de productos
  .gitignore
  restapi/README.md
  restapi/api.ts
  restapi/models/product.ts
  restapi/package.json
  restapi/routes/products.router.ts
  restapi/server.ts
  restapi/services/products.service.ts
Labels: coding

#68 Integración BD
  docs/01_introduction_and_goals.adoc
  package-lock.json
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/products_router.ts
  restapi/routes/users_router.ts
  restapi/server.ts
  restapi/services/DB_manager.ts
  restapi/services/products.service.ts
Labels: coding

#65 Modelo de dominio añadido
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/images/deployment_view.png
  docs/images/domain_model.png
Labels: documentation

#79 Añadido el CRUD de usuarios
  restapi/models/user.ts
  restapi/routes/products_router.ts
  restapi/routes/users_router.ts
  restapi/services/DB_manager.ts
Labels: coding, backend

#81 Gaspar
  webapp/public/images/products/Arabic.jpg
  webapp/public/images/products/Australian.jpg
  webapp/public/images/products/Belgian.jpg
  webapp/public/images/products/British.jpg
  webapp/public/images/products/Bulgarian.jpg
  webapp/public/images/products/French.jpg
  webapp/public/images/products/German.jpg
  webapp/public/images/products/Greek.jpg
  webapp/public/images/products/Hungarian.jpg
  webapp/public/images/products/Indian.jpg
  webapp/public/images/products/Irish.jpg
  webapp/public/images/products/Italian.jpg
  webapp/public/images/products/Japanese.jpg
  webapp/public/images/products/Mexican.jpg
  webapp/public/images/products/Polish.jpg
  webapp/public/images/products/Scotish.jpg
  webapp/public/images/products/SouthAfrican.jpg
  webapp/public/images/products/Spanish.jpg
  webapp/public/images/products/Swedish.jpg
  webapp/public/images/products/Swiss.jpg
  webapp/src/components/Navbar/Navbar.tsx
  webapp/src/components/Products/ProductCard.tsx
  webapp/src/components/Products/ProductList.tsx
  webapp/src/shared/shareddtypes.ts
Labels: frontend

#87 Sign in empezado, footer y navegación
  webapp/package-lock.json
  webapp/package.json
  webapp/public/images/sign-in.png
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Footer.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/Navbar/Navbar.tsx
  webapp/src/components/Products/ProductItem.tsx
  webapp/src/components/User/UserLogIn.tsx
  webapp/src/index.css
  webapp/src/index.tsx
  webapp/src/shared/shareddtypes.ts
Labels: coding, frontend

#103 Roles + encriptación de contraseñas
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/orders_router.ts
  restapi/routes/products_router.ts
  restapi/routes/users_router.ts
  restapi/server.ts
Labels: coding, backend

#102 Terminado: Building Block View
  docs/03_system_scope_and_context.adoc
  docs/05_building_block_view.adoc
  docs/12_glossary.adoc
  docs/images/business_context_diagram.png
  docs/images/technical_context_diagram.png
  docs/images/whitebox_arquisocks.png
  docs/images/whitebox_overall_system.png
  docs/images/whitebox_restapi.png
  docs/images/whitebox_webapp.png
  restapi/services/DB_manager.ts
Labels: documentation

#110 Punto 7 - Deployment View completado
  docs/07_deployment_view.adoc
Labels: documentation

#111 Hecho el diagrama de secuencia: registrar el evento de venta realizada
  docs/06_runtime_view.adoc
Labels: documentation

#113 Inicio de sesión con SOLID
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/Navbar/Navbar.tsx
  webapp/src/components/User/UserLogIn.tsx
  webapp/src/index.css
Labels: coding, frontend
