Repository Arquisoft/dede_es5a, pull requests merged in 2022-04, with the labels that each got.

#121 Punto 8: Cross Cutting Concepts hecho, actualizados ptos 4 y 12
  docs/04_solution_strategy.adoc
  docs/08_concepts.adoc
  docs/12_glossary.adoc
  docs/images/cart.PNG
  docs/images/logIn.PNG
  docs/images/main.PNG
  docs/images/packageLevel1.png
  docs/images/packageLevel2.png
  docs/images/productDetail.PNG
  docs/images/signUp.PNG
  docs/images/userProfile.PNG
Labels: documentation, enhancement

#122 Mensaje de cierre de sesión correcto
  webapp/src/App.tsx
  webapp/src/components/Navbar/Navbar.tsx
Labels: coding, frontend

#124 Requirements overview: Diagrama casos de uso
  docs/01_introduction_and_goals.adoc
Labels: documentation

#127 Paths e identificación hechos
  restapi/routes/users_router.ts
  restapi/server.ts
Labels: coding, backend

#133 Completado el tema del despliegue en Azure
  .github/workflows/asw2122.yml
  .gitignore
  docker-compose-deploy.yml
  docs/01_introduction_and_goals.adoc
  package-lock.json
  restapi/package-lock.json
  webapp/e2e/steps/register-form.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/components/Cart/CartItem.tsx
Labels: deployment

#139 Registro del evento de la venta realizada
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart/ShoppingCart.tsx
  webapp/src/components/Cart/ShoppingCartDrawer.tsx
  webapp/src/components/Navbar/Navbar.tsx
  webapp/src/components/Products/ProductCard.tsx
  webapp/src/components/Stepper/DirectionStepPage.tsx
  webapp/src/components/Stepper/SaleStepper.tsx
  webapp/src/shared/shareddtypes.ts
Labels: frontend

#142 Pantalla de profile del usuario
  package.json
  webapp/package.json
  webapp/public/images/no-image-profile.png
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Navbar/Navbar.tsx
  webapp/src/components/User/UserAddress.tsx
  webapp/src/components/User/UserDetails.tsx
  webapp/src/components/User/UserLogIn.tsx
  webapp/src/index.css
Labels: frontend

#138 Punto 11: Deuda técnica y Punto 9: Decisones de diseño
  .github/workflows/asw2122.yml
  docs/07_deployment_view.adoc
  docs/09_design_decisions.adoc
  docs/11_technical_risks.adoc
Labels: documentation

#163 Corregidas algunas partes de la documentación
  docs/06_runtime_view.adoc
  docs/08_concepts.adoc
  docs/images/arquisocks_architecture.png
  docs/images/navigation_mockups.png
Labels: bug, documentation

#167 Direcciones usuario extraídas
  webapp/src/components/Navbar/Navbar.tsx
  webapp/src/components/User/UserAddress.tsx
  webapp/src/helpers/userAddress.ts
  webapp/src/index.css
Labels: coding, frontend

#179 Imagen de usuario en el nav
  webapp/src/components/Navbar/Navbar.tsx
Labels: coding, frontend

#182 Mejoras para la usabilidad
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart/ShoppingCart.tsx
  webapp/src/components/Cart/ShoppingCartDrawer.tsx
  webapp/src/components/Stepper/DirectionStepPage.tsx
  webapp/src/components/Stepper/Error.tsx
  webapp/src/components/Stepper/PayStepPage.tsx
  webapp/src/components/Stepper/SaleStepper.tsx
  webapp/src/components/Stepper/customisedComponents/CustomisedConnector.ts
  webapp/src/components/Stepper/customisedComponents/CustomisedStepIcon.tsx
  webapp/src/contexts/StepperContext.tsx
  webapp/src/reducers/stepperReducer.ts
Labels: Priority: Critical
